os: linux
language: java
services:
  - docker
cache: bundler
dist: focal
install: skip
jobs:
  include:
    - name: testing
      script: true

notifications:
  email:
    - oksana.hinailo+tbt397@devtactics.net

after_success:
  - echo passed
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
